name: Install SchemaSmith

runs:
  using: "composite"
  steps:
  - name: Generate Script
    run: schemasmith script -o ./publish/cypher-script.cypher -f pokemon.neoschema.yaml
  - name: Upload a Build Artifact
    uses: actions/upload-artifact@v3.1.2
    with:
      name: cypher-script
      path: ./publish
      if-no-files-found: error