name: Release Schema

on:
  workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Install SchemaSmith
      uses: kaiserbergin/schema-smith-actions/.github/actions/install-schema-smith@main
    - name: Lint
      uses: kaiserbergin/schema-smith-actions/.github/actions/lint-neo-schema@main
      with:
        schema_file_path: pokemon.neoschema.yaml
    - name: Generate Script
      uses: kaiserbergin/schema-smith-actions/.github/actions/generate-cypher@main
    - name: Release Schema
      uses: kaiserbergin/schema-smith-actions/.github/actions/run-cypher-script@main
      with:
        server_url: neo4j+s://0404ba3e.databases.neo4j.io
        NEO4J_USERNAME: ${{ secrets.NEO4J_USERNAME }}
        NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}

