name: Release Schema

on:
  workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Install SchemaSmith
      uses: kaiserbergin/schema-smith-actions/.github/actions/install-schema-smith.yml@main
    - name: Lint
      uses: kaiserbergin/schema-smith-actions/.github/actions/lint-neo-schema.yml@main
    - name: Generate Script
      uses: kaiserbergin/schema-smith-actions/.github/actions/generate-cypher.yml@main
    - name: Release Schema
      uses: kaiserbergin/schema-smith-actions/.github/actions/run-cypher-script.yml@main
      with:
        server_url: neo4j+s://0404ba3e.databases.neo4j.io:7687
        NEO4J_USERNAME: ${{ secrets.NEO4J_USERNAME }}
        NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}

