name: PR Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-publish:
    uses: kaiserbergin/schema-smith-actions/.github/workflows/schema-smith-lint-and-publish.yml@main
